document.writeln("<header>");
document.writeln("    <div class=\"nav\">");
document.writeln("        <span class=\"logo fl\"><img src=\"./img/logo.png\" alt=\"\"></span>");
document.writeln("        <ul class=\"title fl\">");
document.writeln("            <li class=\"active_title\">网上沙龙</li>");
document.writeln("            <li>基金理财</li>");
document.writeln("            <li>定制账户</li>");
document.writeln("            <li>热点快讯</li>");
document.writeln("            <li>基金理财</li>");
document.writeln("            <li>定制账户</li>");
document.writeln("            <li>热点快讯</li>");
document.writeln("            <li>基金理财</li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"fr\">");
document.writeln("            <span ><img src=\"./img/search.png\" alt=\"\" style=\"margin-right: 60px;\"></span>");
document.writeln("            <span class=\"hidden\"><img src=\"./img/close.png\" alt=\"\" style=\"margin-right: 60px;\"></span>");
document.writeln("            <span><img src=\"./img/liebiao-.png\" alt=\"\"></span>");
document.writeln("        </div>");
document.writeln("        <div class=\"searchBox hidden\">");
document.writeln("            <span style=\"position: absolute;top: 8px;left: 20px;height: 30px;\"><img src=\"./img/search.png\" alt=\"\" ></span>");
document.writeln("            <input type=\"text\" id=\"search_val\" placeholder=\"输入节目标题或嘉宾\" >");
document.writeln("            <div class=\"search_list\">");
document.writeln("                <ul>");
document.writeln("                    <li>等等方法的</li>");
document.writeln("                    <li>等等方法的</li>");
document.writeln("                    <li>等等方法的</li>");
document.writeln("                    <li>等等方法的</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"rank_box hidden\">");
document.writeln("            <h5>排行榜</h5>");
document.writeln("            <ul>");
document.writeln("                <li><span>1</span>的鬼地方个</li>");
document.writeln("                <li><span>1</span>的鬼地方个</li>");
document.writeln("                <li><span>1</span>的鬼地方个</li>");
document.writeln("                <li><span>1</span>的鬼地方个</li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");